imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        save_path: %kernel.root_dir%/sessions/
        # handler_id set to null will use default session handler from php.ini
        # handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'DanMainBundle:Form:theme.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DanMainBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class:     Dan\UserBundle\Entity\User
  
    group:
        group_class: Dan\UserBundle\Entity\Group

    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: model.manager.user
    from_email:
        address:        noreply@symfonyapp.com
        sender_name:    Blab
    registration:
        form: 
            type: dan_user_registration
        confirmation:
            enabled:    true
            template: DanUserBundle:User:confirmation.email.twig
            from_email:
                address:        confirmation@symfonyapp.com
                sender_name:    Blab Registration
    change_password:
        form: 
            type: dan_user_change_password
    profile:
        form:
            type: dan_user_profile_account
    
    resetting:
        form: 
            type: dan_user_resetting
        email:
            template: DanUserBundle:User:resetting.email.twig
            from_email:
                address:        resetting@symfonyapp.com
                sender_name:    Blab Resetting

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
          
          

sonata_admin:
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    security:
        handler: sonata.admin.security.handler.acl

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

sonata_user:
    security_acl: true
    manager_type: orm
    class:                 
        user:  Dan\UserBundle\Entity\User
        group: Dan\UserBundle\Entity\Group
        
liip_doctrine_cache:
    namespaces:
        bgg:
            type: file_system
            

avalanche_imagine:
    source_root: %kernel.root_dir%/files/images
    filters:
        mini:
            type:    thumbnail
            options: { size: [30, 30], mode: outbound, absolute: true }
        player_main:
            type:    thumbnail
            options: { size: [30, 30], mode: outbound, absolute: true }
        player_joined:
            type:    thumbnail
            options: { size: [25, 25], mode: outbound, absolute: true }
        player_guest:
            type:    thumbnail
            options: { size: [20, 20], mode: outbound, absolute: true }
            
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable: false
            loggable: false
            translatable: false
            sortable: false
            
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@DanUserBundle/Resources/config/serializer/FOS"
            SonataUserBundle:
                namespace_prefix: Sonata\UserBundle
                path: "@DanUserBundle/Resources/config/serializer/Sonata"
          
hwi_oauth:
    firewall_name: main
    connect:
        account_connector: oauth.user_provider
    fosub:
        username_iterations: 30
        properties:
            google: googleId
    resource_owners:
        google:
            type:                google
            client_id:           %google_client_id%
            client_secret:       %google_client_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        facebook:
            type:                facebook
            client_id:          %facebook_client_id%
            client_secret:      %facebook_client_secret%
            infos_url:          "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                username: username
                name: name
                email: email
                profilepicture: picture.data.url
            scope:              "email"


trt_async_tasks:
    # This prefix allows the dispatcher to detect async event,
    # if you want use another prefix put here
    event:
        prefix: async_
    mq:
        # The rabbitMq host / port
        connection_params:
            host: %mq_host%
            port: %mq_port%
        # Define the exchange name for rabbitmq
        exchange:
            exchange: 'exchange_symfony_events'
            
            
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/google/wkhtmltopdf-i386/wkhtmltopdf-i386
        options:    []