security:
    
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
#            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        chain_provider:
            chain:
                providers: 
                    - fos_userbundle
                    - oauth
        fos_userbundle:
            id: fos_user.user_provider.username_email
        oauth:
            id: oauth.user_provider
#        google_provider:
#            id: hwi_oauth.user.provider
#        fos_googlebundle:
#            id: fos_google.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            ^/admin(.*)
            switch_user:        true
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:    true
#            oauth:
#                resource_owners:
#                  google:          "/admin/login/check-google"
#                  facebook:        "/admin/login/check-facebook"
#                login_path:        /admin/login
#                failure_path:      /admin/login
#                oauth_user_provider:
#                    service: oauth.user_provider
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 giorni in secondi
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

        main:
            pattern: ^/
#            fos_google:
#                provider: fos_googlebundle
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                    facebook:           "/login/check-facebook"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: oauth.user_provider
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 giorni in secondi
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            
    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_google

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }


    acl:
        connection: default
        
