FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        username:
            expose: true
            type: string
        email:
            expose: true
            type: string
